version: '3.4'

networks:
  webapi:
    driver: bridge

services:
  dockerwebapi:
    container_name: docker-web-api
    image: ${DOCKER_REGISTRY-}dockerwebapi
    build:
      context: .
      dockerfile: DockerWebApi/Dockerfile
    #Only map and expose ports if you need a constant accessible port for the service (e.g. for debugging)
    #ports:
    #   - "5000:80"
    #   - "5001:443"
    networks: 
      - webapi
  dockerwebapi2:
    container_name: docker-web-api2
    image: ${DOCKER_REGISTRY-}dockerwebapi2
    build:
      context: .
      dockerfile: DockerWebApi2/Dockerfile
    #Only map and expose ports if you need a constant accessible port for the service (e.g. for debugging)
    #ports:
    #   - "5004:80"
    #   - "5005:443"
    networks: 
      - webapi
  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
    #   - "5002:80"
       - "5003:443"
    networks:
      - webapi
  demosqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=J0HN_BA3ER
    restart: always
    networks:
        - webapi 